<?php

declare(strict_types=1);

namespace Alexandria\Core\Database\Seeders;

use Alexandria\Core\Models\AiModel;
use Alexandria\Core\Models\AiProvider;
use Illuminate\Database\Seeder;

/**
 * AI Model Seeder
 *
 * Seeds comprehensive AI model data with current pricing from official sources.
 * Pricing updated: December 2025
 *
 * Sources:
 * - Google: https://ai.google.dev/gemini-api/docs/pricing
 * - OpenAI: https://openai.com/api/pricing/
 * - Anthropic: https://platform.claude.com/docs/en/about-claude/pricing
 * - fal.ai: https://fal.ai/pricing
 */
class AiModelSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedGoogleModels();
        $this->seedOpenAiModels();
        $this->seedAnthropicModels();
        $this->seedFalModels();
    }

    private function seedGoogleModels(): void
    {
        $provider = AiProvider::where('slug', 'google')->first();
        if (! $provider) {
            return;
        }

        $models = [
            // ============================================
            // Gemini 3 Series (Latest Flagship) - Dec 2025
            // ============================================
            [
                'model_id' => 'gemini-3-pro-preview',
                'display_name' => 'Gemini 3 Pro Preview',
                'category' => 'general',
                'context_window' => 1048576,
                'input_price_per_million' => 2.00,
                'output_price_per_million' => 12.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Most intelligent model. 65K output. Thinking, search grounding. Knowledge: Jan 2025',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use', 'agentic', 'search_grounding'],
                'released_at' => '2025-11-18',
            ],
            [
                'model_id' => 'gemini-3-pro-image-preview',
                'display_name' => 'Nano Banana Pro',
                'category' => 'image',
                'context_window' => 65536,
                'input_price_per_million' => 2.00,
                'output_price_per_million' => 12.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Professional image generation with Thinking. High-fidelity text rendering. 32K output.',
                'capabilities' => ['image_generation', 'vision', 'extended_thinking'],
                'released_at' => '2025-11-18',
            ],
            [
                'model_id' => 'gemini-3-flash-preview',
                'display_name' => 'Gemini 3 Flash Preview',
                'category' => 'fast',
                'context_window' => 1048576,
                'input_price_per_million' => 0.50,
                'output_price_per_million' => 3.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Frontier intelligence + speed. 65K output. Thinking, search grounding. Dec 2025',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use', 'search_grounding'],
                'released_at' => '2025-12-19',
            ],

            // ============================================
            // Gemini 2.5 Series (Stable) - Current Best Value
            // ============================================
            [
                'model_id' => 'gemini-2.5-pro',
                'display_name' => 'Gemini 2.5 Pro',
                'category' => 'general',
                'context_window' => 1048576,
                'input_price_per_million' => 1.25,
                'output_price_per_million' => 10.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'SOTA thinking model. 65K output. Long context (>200K): $2.50/$15. Jun 2025',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use', 'search_grounding'],
                'released_at' => '2025-06-17',
            ],
            [
                'model_id' => 'gemini-2.5-flash',
                'display_name' => 'Gemini 2.5 Flash',
                'category' => 'fast',
                'context_window' => 1048576,
                'input_price_per_million' => 0.30,
                'output_price_per_million' => 2.50,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Best price-performance. 65K output. Thinking tokens. Jun 2025',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use', 'search_grounding'],
                'released_at' => '2025-06-17',
            ],
            [
                'model_id' => 'gemini-2.5-flash-lite',
                'display_name' => 'Gemini 2.5 Flash Lite',
                'category' => 'fast',
                'context_window' => 1048576,
                'input_price_per_million' => 0.10,
                'output_price_per_million' => 0.40,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Ultra fast, most cost-effective. 65K output. Thinking tokens. Jul 2025',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use', 'search_grounding'],
                'released_at' => '2025-06-17',
            ],

            // ============================================
            // Gemini Latest Aliases (Auto-updated)
            // ============================================
            [
                'model_id' => 'gemini-flash-latest',
                'display_name' => 'Gemini Flash Latest',
                'category' => 'fast',
                'context_window' => 1048576,
                'input_price_per_million' => 0.30,
                'output_price_per_million' => 2.50,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Alias → latest stable flash. Hot-swapped with 2-week notice.',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use'],
                'released_at' => '2025-06-17',
            ],
            [
                'model_id' => 'gemini-flash-lite-latest',
                'display_name' => 'Gemini Flash Lite Latest',
                'category' => 'fast',
                'context_window' => 1048576,
                'input_price_per_million' => 0.10,
                'output_price_per_million' => 0.40,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Alias → latest stable flash-lite. Hot-swapped with 2-week notice.',
                'released_at' => '2025-06-17',
            ],

            // ============================================
            // Gemini 2.0 Series (Previous Gen)
            // ============================================
            [
                'model_id' => 'gemini-2.0-flash',
                'display_name' => 'Gemini 2.0 Flash',
                'category' => 'fast',
                'context_window' => 1048576,
                'input_price_per_million' => 0.10,
                'output_price_per_million' => 0.40,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Workhorse model. 8K output. Feb 2025. Knowledge: Aug 2024',
                'released_at' => '2025-02-25',
            ],
            [
                'model_id' => 'gemini-2.0-flash-lite',
                'display_name' => 'Gemini 2.0 Flash Lite',
                'category' => 'fast',
                'context_window' => 1048576,
                'input_price_per_million' => 0.075,
                'output_price_per_million' => 0.30,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Cost-efficient 2.0. 8K output. Feb 2025. Knowledge: Aug 2024',
                'released_at' => '2025-02-25',
            ],
            [
                'model_id' => 'gemini-2.0-flash-thinking',
                'display_name' => 'Gemini 2.0 Flash Thinking',
                'category' => 'analyst',
                'context_window' => 1048576,
                'input_price_per_million' => 0.10,
                'output_price_per_million' => 0.40,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Experimental thinking. Use 2.5+ for thinking instead.',
                'capabilities' => ['extended_thinking'],
                'released_at' => '2025-02-25',
            ],

            // ============================================
            // Gemini 1.5 Series (Legacy - Consider Deprecating)
            // ============================================
            [
                'model_id' => 'gemini-1.5-pro',
                'display_name' => 'Gemini 1.5 Pro',
                'category' => 'general',
                'context_window' => 2097152,
                'input_price_per_million' => 1.25,
                'output_price_per_million' => 5.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '2M context window (largest). Long context (>128K): $2.50/$10. Legacy.',
                'released_at' => '2024-05-14',
            ],
            [
                'model_id' => 'gemini-1.5-flash',
                'display_name' => 'Gemini 1.5 Flash',
                'category' => 'fast',
                'context_window' => 1048576,
                'input_price_per_million' => 0.075,
                'output_price_per_million' => 0.30,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '1M context. Long context (>128K): $0.15/$0.60. Legacy.',
                'released_at' => '2024-05-14',
            ],
            [
                'model_id' => 'gemini-1.5-flash-8b',
                'display_name' => 'Gemini 1.5 Flash 8B',
                'category' => 'fast',
                'context_window' => 1048576,
                'input_price_per_million' => 0.0375,
                'output_price_per_million' => 0.15,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Smallest 1.5 model. Use 2.5 Flash Lite instead.',
                'released_at' => '2024-10-03',
            ],

            // ============================================
            // Image Generation Models
            // ============================================
            [
                'model_id' => 'gemini-2.5-flash-image',
                'display_name' => 'Nano Banana',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => 0.30,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Fast native image generation. High-volume, low-latency. $0.039/image',
                'released_at' => '2025-11-18',
            ],
            [
                'model_id' => 'imagen-4.0-generate-001',
                'display_name' => 'Imagen 4',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Latest image generation. Better text rendering, overall quality. $0.04/image',
                'released_at' => '2025-11-18',
            ],
            [
                'model_id' => 'imagen-4.0-ultra-generate-001',
                'display_name' => 'Imagen 4 Ultra',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_flagship' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Highest quality image generation. $0.06/image',
                'released_at' => '2025-11-18',
            ],
            [
                'model_id' => 'imagen-3.0-generate-002',
                'display_name' => 'Imagen 3',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.03/image',
                'released_at' => '2024-12-10',
            ],

            // ============================================
            // Video Generation Models
            // ============================================
            [
                'model_id' => 'veo-3.1-generate-preview',
                'display_name' => 'Veo 3.1 Standard',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.40/second',
                'released_at' => '2025-12-19',
            ],
            [
                'model_id' => 'veo-3.1-fast-generate-preview',
                'display_name' => 'Veo 3.1 Fast',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.15/second',
                'released_at' => '2025-12-19',
            ],
            [
                'model_id' => 'veo-2.0-generate-001',
                'display_name' => 'Veo 2',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.35/second',
                'released_at' => '2025-05-20',
            ],

            // ============================================
            // Embeddings
            // ============================================
            [
                'model_id' => 'gemini-embedding-001',
                'display_name' => 'Gemini Embedding',
                'category' => 'embedding',
                'context_window' => null,
                'input_price_per_million' => 0.15,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Text embeddings. Batch: $0.075/MTok',
                'released_at' => '2025-06-17',
            ],

            // ============================================
            // Audio/TTS Models
            // ============================================
            [
                'model_id' => 'gemini-2.5-flash-native-audio-preview',
                'display_name' => 'Gemini 2.5 Flash Native Audio',
                'category' => 'audio',
                'context_window' => null,
                'input_price_per_million' => 0.50,
                'output_price_per_million' => 2.00,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Audio input: $3.00/MTok, Audio output: $12.00/MTok',
                'released_at' => '2025-06-17',
            ],

            // ============================================
            // Open Models (Free)
            // ============================================
            [
                'model_id' => 'gemma-3',
                'display_name' => 'Gemma 3',
                'category' => 'general',
                'context_window' => 128000,
                'input_price_per_million' => 0.00,
                'output_price_per_million' => 0.00,
                'supports_json_mode' => true,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Free open model',
                'released_at' => '2025-03-12',
            ],
        ];

        foreach ($models as $model) {
            AiModel::updateOrCreate(
                ['model_id' => $model['model_id']],
                array_merge($model, ['ai_provider_id' => $provider->id])
            );
        }
    }

    private function seedOpenAiModels(): void
    {
        $provider = AiProvider::where('slug', 'openai')->first();
        if (! $provider) {
            return;
        }

        $models = [
            // ============================================
            // GPT-5 Series (Latest)
            // ============================================
            [
                'model_id' => 'gpt-5.2',
                'display_name' => 'GPT-5.2',
                'category' => 'general',
                'context_window' => 128000,
                'input_price_per_million' => 1.75,
                'output_price_per_million' => 14.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Latest flagship. Cached: $0.175/MTok',
                'released_at' => '2025-12-17',
            ],
            [
                'model_id' => 'gpt-5.1',
                'display_name' => 'GPT-5.1',
                'category' => 'general',
                'context_window' => 128000,
                'input_price_per_million' => 1.25,
                'output_price_per_million' => 10.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Cached: $0.125/MTok',
                'released_at' => '2025-10-01',
            ],
            [
                'model_id' => 'gpt-5',
                'display_name' => 'GPT-5',
                'category' => 'general',
                'context_window' => 128000,
                'input_price_per_million' => 1.25,
                'output_price_per_million' => 10.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Cached: $0.125/MTok',
                'released_at' => '2025-08-07',
            ],
            [
                'model_id' => 'gpt-5-mini',
                'display_name' => 'GPT-5 Mini',
                'category' => 'fast',
                'context_window' => 128000,
                'input_price_per_million' => 0.25,
                'output_price_per_million' => 2.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Fast & affordable. Cached: $0.025/MTok',
                'released_at' => '2025-08-07',
            ],
            [
                'model_id' => 'gpt-5-nano',
                'display_name' => 'GPT-5 Nano',
                'category' => 'fast',
                'context_window' => 128000,
                'input_price_per_million' => 0.05,
                'output_price_per_million' => 0.40,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Most affordable. Cached: $0.005/MTok',
                'released_at' => '2025-08-07',
            ],
            [
                'model_id' => 'gpt-5.2-pro',
                'display_name' => 'GPT-5.2 Pro',
                'category' => 'creative',
                'context_window' => 128000,
                'input_price_per_million' => 21.00,
                'output_price_per_million' => 168.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Premium quality output',
                'released_at' => '2025-12-17',
            ],
            [
                'model_id' => 'gpt-5-pro',
                'display_name' => 'GPT-5 Pro',
                'category' => 'creative',
                'context_window' => 128000,
                'input_price_per_million' => 15.00,
                'output_price_per_million' => 120.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Premium quality output',
                'released_at' => '2025-08-07',
            ],

            // ============================================
            // GPT-4.1 Series
            // ============================================
            [
                'model_id' => 'gpt-4.1',
                'display_name' => 'GPT-4.1',
                'category' => 'general',
                'context_window' => 128000,
                'input_price_per_million' => 2.00,
                'output_price_per_million' => 8.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Cached: $0.50/MTok',
                'released_at' => '2025-04-14',
            ],
            [
                'model_id' => 'gpt-4.1-mini',
                'display_name' => 'GPT-4.1 Mini',
                'category' => 'fast',
                'context_window' => 128000,
                'input_price_per_million' => 0.40,
                'output_price_per_million' => 1.60,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Cached: $0.10/MTok',
                'released_at' => '2025-04-14',
            ],
            [
                'model_id' => 'gpt-4.1-nano',
                'display_name' => 'GPT-4.1 Nano',
                'category' => 'fast',
                'context_window' => 128000,
                'input_price_per_million' => 0.10,
                'output_price_per_million' => 0.40,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Cached: $0.025/MTok',
                'released_at' => '2025-04-14',
            ],

            // ============================================
            // GPT-4o Series
            // ============================================
            [
                'model_id' => 'gpt-4o',
                'display_name' => 'GPT-4o',
                'category' => 'general',
                'context_window' => 128000,
                'input_price_per_million' => 2.50,
                'output_price_per_million' => 10.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Reliable workhorse. Cached: $1.25/MTok',
                'released_at' => '2024-05-13',
            ],
            [
                'model_id' => 'gpt-4o-mini',
                'display_name' => 'GPT-4o Mini',
                'category' => 'fast',
                'context_window' => 128000,
                'input_price_per_million' => 0.15,
                'output_price_per_million' => 0.60,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Most cost-effective 4o. Cached: $0.075/MTok',
                'released_at' => '2024-07-18',
            ],
            [
                'model_id' => 'gpt-4o-2024-05-13',
                'display_name' => 'GPT-4o (May 2024)',
                'category' => 'general',
                'context_window' => 128000,
                'input_price_per_million' => 5.00,
                'output_price_per_million' => 15.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Legacy snapshot',
                'released_at' => '2024-05-13',
            ],

            // ============================================
            // O-Series (Reasoning Models)
            // ============================================
            [
                'model_id' => 'o1',
                'display_name' => 'O1',
                'category' => 'analyst',
                'context_window' => 200000,
                'input_price_per_million' => 15.00,
                'output_price_per_million' => 60.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Advanced reasoning. Cached: $7.50/MTok',
                'released_at' => '2024-12-17',
            ],
            [
                'model_id' => 'o1-pro',
                'display_name' => 'O1 Pro',
                'category' => 'analyst',
                'context_window' => 200000,
                'input_price_per_million' => 150.00,
                'output_price_per_million' => 600.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Maximum reasoning capability',
                'released_at' => '2025-03-19',
            ],
            [
                'model_id' => 'o1-mini',
                'display_name' => 'O1 Mini',
                'category' => 'analyst',
                'context_window' => 128000,
                'input_price_per_million' => 1.10,
                'output_price_per_million' => 4.40,
                'supports_json_mode' => true,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Cached: $0.55/MTok',
                'released_at' => '2024-09-12',
            ],
            [
                'model_id' => 'o3',
                'display_name' => 'O3',
                'category' => 'analyst',
                'context_window' => 200000,
                'input_price_per_million' => 2.00,
                'output_price_per_million' => 8.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Latest reasoning model. Cached: $0.50/MTok',
                'released_at' => '2025-04-16',
            ],
            [
                'model_id' => 'o3-pro',
                'display_name' => 'O3 Pro',
                'category' => 'analyst',
                'context_window' => 200000,
                'input_price_per_million' => 20.00,
                'output_price_per_million' => 80.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Enhanced O3 reasoning',
                'released_at' => '2025-06-10',
            ],
            [
                'model_id' => 'o3-mini',
                'display_name' => 'O3 Mini',
                'category' => 'analyst',
                'context_window' => 200000,
                'input_price_per_million' => 1.10,
                'output_price_per_million' => 4.40,
                'supports_json_mode' => true,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Fast reasoning. Cached: $0.55/MTok',
                'released_at' => '2025-01-31',
            ],
            [
                'model_id' => 'o3-deep-research',
                'display_name' => 'O3 Deep Research',
                'category' => 'analyst',
                'context_window' => 200000,
                'input_price_per_million' => 10.00,
                'output_price_per_million' => 40.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Extended research mode. Cached: $2.50/MTok',
                'released_at' => '2025-06-26',
            ],
            [
                'model_id' => 'o4-mini',
                'display_name' => 'O4 Mini',
                'category' => 'analyst',
                'context_window' => 200000,
                'input_price_per_million' => 1.10,
                'output_price_per_million' => 4.40,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Latest mini reasoning. Cached: $0.275/MTok',
                'released_at' => '2025-04-16',
            ],
            [
                'model_id' => 'o4-mini-deep-research',
                'display_name' => 'O4 Mini Deep Research',
                'category' => 'analyst',
                'context_window' => 200000,
                'input_price_per_million' => 2.00,
                'output_price_per_million' => 8.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Mini with deep research. Cached: $0.50/MTok',
                'released_at' => '2025-04-16',
            ],

            // ============================================
            // Realtime & Audio Models
            // ============================================
            [
                'model_id' => 'gpt-realtime',
                'display_name' => 'GPT Realtime',
                'category' => 'audio',
                'context_window' => 128000,
                'input_price_per_million' => 4.00,
                'output_price_per_million' => 16.00,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Audio: $32 in/$64 out per MTok',
                'released_at' => '2025-03-20',
            ],
            [
                'model_id' => 'gpt-realtime-mini',
                'display_name' => 'GPT Realtime Mini',
                'category' => 'audio',
                'context_window' => 128000,
                'input_price_per_million' => 0.60,
                'output_price_per_million' => 2.40,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Audio: $10 in/$20 out per MTok',
                'released_at' => '2025-03-20',
            ],
            [
                'model_id' => 'gpt-audio',
                'display_name' => 'GPT Audio',
                'category' => 'audio',
                'context_window' => 128000,
                'input_price_per_million' => 2.50,
                'output_price_per_million' => 10.00,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Audio tokens: $32 in/$64 out per MTok',
                'released_at' => '2024-12-17',
            ],

            // ============================================
            // Image Generation Models
            // ============================================
            [
                'model_id' => 'gpt-image-1.5',
                'display_name' => 'GPT Image 1.5',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => 5.00,
                'output_price_per_million' => 10.00,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Low: $0.009, Med: $0.034, High: $0.133 per image',
                'released_at' => '2025-12-17',
            ],
            [
                'model_id' => 'gpt-image-1',
                'display_name' => 'GPT Image 1',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => 5.00,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Low: $0.011, Med: $0.042, High: $0.167 per image',
                'released_at' => '2025-04-23',
            ],
            [
                'model_id' => 'gpt-image-1-mini',
                'display_name' => 'GPT Image 1 Mini',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => 2.00,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Low: $0.005, Med: $0.011, High: $0.036 per image',
                'released_at' => '2025-04-23',
            ],
            [
                'model_id' => 'dall-e-3',
                'display_name' => 'DALL-E 3',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Standard: $0.04, HD: $0.08 per 1024x1024',
                'released_at' => '2023-10-01',
            ],
            [
                'model_id' => 'dall-e-2',
                'display_name' => 'DALL-E 2',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.016-$0.02 per image',
                'released_at' => '2022-04-06',
            ],

            // ============================================
            // Video Generation
            // ============================================
            [
                'model_id' => 'sora-2',
                'display_name' => 'Sora 2',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.10/second (720p/1280p)',
                'released_at' => '2025-12-17',
            ],
            [
                'model_id' => 'sora-2-pro',
                'display_name' => 'Sora 2 Pro',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_flagship' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.30/sec (720p), $0.50/sec (1024p+)',
                'released_at' => '2025-12-17',
            ],

            // ============================================
            // Embeddings
            // ============================================
            [
                'model_id' => 'text-embedding-3-small',
                'display_name' => 'Text Embedding 3 Small',
                'category' => 'embedding',
                'context_window' => 8191,
                'input_price_per_million' => 0.02,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Batch: $0.01/MTok',
                'released_at' => '2024-01-25',
            ],
            [
                'model_id' => 'text-embedding-3-large',
                'display_name' => 'Text Embedding 3 Large',
                'category' => 'embedding',
                'context_window' => 8191,
                'input_price_per_million' => 0.13,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Higher quality. Batch: $0.065/MTok',
                'released_at' => '2024-01-25',
            ],
            [
                'model_id' => 'text-embedding-ada-002',
                'display_name' => 'Text Embedding Ada 002',
                'category' => 'embedding',
                'context_window' => 8191,
                'input_price_per_million' => 0.10,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Legacy. Batch: $0.05/MTok',
                'released_at' => '2022-12-15',
            ],

            // ============================================
            // Transcription & TTS
            // ============================================
            [
                'model_id' => 'whisper-1',
                'display_name' => 'Whisper',
                'category' => 'audio',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Transcription: $0.006/minute',
                'released_at' => '2023-03-01',
            ],
            [
                'model_id' => 'tts-1',
                'display_name' => 'TTS',
                'category' => 'audio',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Speech generation: $15/1M characters',
                'released_at' => '2023-11-06',
            ],
            [
                'model_id' => 'tts-1-hd',
                'display_name' => 'TTS HD',
                'category' => 'audio',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'HD speech: $30/1M characters',
                'released_at' => '2023-11-06',
            ],

            // ============================================
            // Computer Use
            // ============================================
            [
                'model_id' => 'computer-use-preview',
                'display_name' => 'Computer Use Preview',
                'category' => 'agent',
                'context_window' => 128000,
                'input_price_per_million' => 3.00,
                'output_price_per_million' => 12.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Computer control agent',
                'released_at' => '2025-03-27',
            ],

            // ============================================
            // Codex Models
            // ============================================
            [
                'model_id' => 'gpt-5.1-codex',
                'display_name' => 'GPT-5.1 Codex',
                'category' => 'general',
                'context_window' => 128000,
                'input_price_per_million' => 1.25,
                'output_price_per_million' => 10.00,
                'supports_json_mode' => true,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Optimized for code. Cached: $0.125/MTok',
                'released_at' => '2025-10-01',
            ],
            [
                'model_id' => 'gpt-5.1-codex-mini',
                'display_name' => 'GPT-5.1 Codex Mini',
                'category' => 'fast',
                'context_window' => 128000,
                'input_price_per_million' => 0.25,
                'output_price_per_million' => 2.00,
                'supports_json_mode' => true,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Fast code assistant. Cached: $0.025/MTok',
                'released_at' => '2025-10-01',
            ],

            // ============================================
            // Legacy Models
            // ============================================
            [
                'model_id' => 'gpt-4-turbo',
                'display_name' => 'GPT-4 Turbo',
                'category' => 'general',
                'context_window' => 128000,
                'input_price_per_million' => 10.00,
                'output_price_per_million' => 30.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Legacy. Batch: $5/$15',
                'released_at' => '2024-04-09',
            ],
            [
                'model_id' => 'gpt-4',
                'display_name' => 'GPT-4',
                'category' => 'general',
                'context_window' => 8192,
                'input_price_per_million' => 30.00,
                'output_price_per_million' => 60.00,
                'supports_json_mode' => true,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => false,
                'notes' => 'Deprecated. Use GPT-4o or newer',
                'released_at' => '2023-03-14',
            ],
            [
                'model_id' => 'gpt-3.5-turbo',
                'display_name' => 'GPT-3.5 Turbo',
                'category' => 'fast',
                'context_window' => 16385,
                'input_price_per_million' => 3.00,
                'output_price_per_million' => 6.00,
                'supports_json_mode' => true,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Legacy. Batch: $0.25/$0.75',
                'released_at' => '2023-03-01',
            ],
        ];

        foreach ($models as $model) {
            AiModel::updateOrCreate(
                ['model_id' => $model['model_id']],
                array_merge($model, ['ai_provider_id' => $provider->id])
            );
        }
    }

    private function seedAnthropicModels(): void
    {
        $provider = AiProvider::where('slug', 'anthropic')->first();
        if (! $provider) {
            return;
        }

        $models = [
            // ============================================
            // Claude 4.5 Series (Latest)
            // ============================================
            [
                'model_id' => 'claude-opus-4-5-20251101',
                'display_name' => 'Claude Opus 4.5',
                'category' => 'creative',
                'context_window' => 200000,
                'input_price_per_million' => 5.00,
                'output_price_per_million' => 25.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Premium intelligence. Cache: $6.25 write, $0.50 read/MTok',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use'],
                'released_at' => '2025-11-01',
            ],
            [
                'model_id' => 'claude-sonnet-4-5-20250929',
                'display_name' => 'Claude Sonnet 4.5',
                'category' => 'general',
                'context_window' => 200000,
                'input_price_per_million' => 3.00,
                'output_price_per_million' => 15.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Best balance. 1M context beta. Cache: $3.75 write, $0.30 read. Long (>200K): $6/$22.50',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use', '1m_context_beta'],
                'released_at' => '2025-09-29',
            ],
            [
                'model_id' => 'claude-haiku-4-5-20251001',
                'display_name' => 'Claude Haiku 4.5',
                'category' => 'fast',
                'context_window' => 200000,
                'input_price_per_million' => 1.00,
                'output_price_per_million' => 5.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Fastest Claude. Cache: $1.25 write, $0.10 read/MTok',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use'],
                'released_at' => '2025-10-01',
            ],

            // ============================================
            // Claude 4.1 Series
            // ============================================
            [
                'model_id' => 'claude-opus-4-1-20250805',
                'display_name' => 'Claude Opus 4.1',
                'category' => 'creative',
                'context_window' => 200000,
                'input_price_per_million' => 15.00,
                'output_price_per_million' => 75.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Cache: $18.75 write, $1.50 read/MTok',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use'],
                'released_at' => '2025-08-05',
            ],

            // ============================================
            // Claude 4 Series
            // ============================================
            [
                'model_id' => 'claude-sonnet-4-20250514',
                'display_name' => 'Claude Sonnet 4',
                'category' => 'general',
                'context_window' => 200000,
                'input_price_per_million' => 3.00,
                'output_price_per_million' => 15.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '1M context beta. Cache: $3.75 write, $0.30 read. Long (>200K): $6/$22.50',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use', '1m_context_beta'],
                'released_at' => '2025-05-14',
            ],
            [
                'model_id' => 'claude-opus-4-20250514',
                'display_name' => 'Claude Opus 4',
                'category' => 'creative',
                'context_window' => 200000,
                'input_price_per_million' => 15.00,
                'output_price_per_million' => 75.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Cache: $18.75 write, $1.50 read/MTok',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use'],
                'released_at' => '2025-05-14',
            ],

            // ============================================
            // Claude 3.x Series (Legacy)
            // ============================================
            [
                'model_id' => 'claude-3-7-sonnet-20250219',
                'display_name' => 'Claude 3.7 Sonnet',
                'category' => 'general',
                'context_window' => 200000,
                'input_price_per_million' => 3.00,
                'output_price_per_million' => 15.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Deprecated. Cache: $3.75 write, $0.30 read. 128K output beta.',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use'],
                'released_at' => '2025-02-24',
            ],
            [
                'model_id' => 'claude-3-5-haiku-20241022',
                'display_name' => 'Claude 3.5 Haiku',
                'category' => 'fast',
                'context_window' => 200000,
                'input_price_per_million' => 0.80,
                'output_price_per_million' => 4.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Cache: $1.00 write, $0.08 read/MTok',
                'capabilities' => ['vision', 'tool_use'],
                'released_at' => '2024-10-22',
            ],
            [
                'model_id' => 'claude-3-opus-20240229',
                'display_name' => 'Claude 3 Opus',
                'category' => 'creative',
                'context_window' => 200000,
                'input_price_per_million' => 15.00,
                'output_price_per_million' => 75.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Deprecated. Cache: $18.75 write, $1.50 read/MTok',
                'capabilities' => ['vision', 'tool_use'],
                'released_at' => '2024-02-29',
            ],
            [
                'model_id' => 'claude-3-haiku-20240307',
                'display_name' => 'Claude 3 Haiku',
                'category' => 'fast',
                'context_window' => 200000,
                'input_price_per_million' => 0.25,
                'output_price_per_million' => 1.25,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Most affordable Claude. Cache: $0.30 write, $0.03 read/MTok',
                'capabilities' => ['vision', 'tool_use'],
                'released_at' => '2024-03-07',
            ],
        ];

        foreach ($models as $model) {
            AiModel::updateOrCreate(
                ['model_id' => $model['model_id']],
                array_merge($model, ['ai_provider_id' => $provider->id])
            );
        }
    }

    private function seedFalModels(): void
    {
        $provider = AiProvider::where('slug', 'fal')->first();
        if (! $provider) {
            return;
        }

        $models = [
            // ============================================
            // Flux Series (Black Forest Labs via fal.ai)
            // ============================================
            [
                'model_id' => 'fal-ai/flux-pro/v1.1-ultra',
                'display_name' => 'Flux Pro 1.1 Ultra',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Highest quality Flux. $0.06/megapixel',
                'released_at' => '2024-11-01',
            ],
            [
                'model_id' => 'fal-ai/flux-pro',
                'display_name' => 'Flux Pro',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Professional quality. $0.05/megapixel',
                'released_at' => '2024-08-01',
            ],
            [
                'model_id' => 'fal-ai/flux/dev',
                'display_name' => 'Flux Dev',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Development model. $0.025/megapixel',
                'released_at' => '2024-08-01',
            ],
            [
                'model_id' => 'fal-ai/flux/schnell',
                'display_name' => 'Flux Schnell',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Fast generation. $0.003/megapixel',
                'released_at' => '2024-08-01',
            ],
            [
                'model_id' => 'fal-ai/flux-realism',
                'display_name' => 'Flux Realism',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Photorealistic focus. $0.025/megapixel',
                'released_at' => '2024-08-01',
            ],

            // ============================================
            // Z-Image Series (Tongyi-MAI)
            // ============================================
            [
                'model_id' => 'fal-ai/z-image/turbo',
                'display_name' => 'Z-Image Turbo',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '6B param, super fast. $0.005/megapixel',
                'released_at' => '2025-01-15',
            ],

            // ============================================
            // Stable Diffusion Series
            // ============================================
            [
                'model_id' => 'fal-ai/stable-diffusion-v35-large',
                'display_name' => 'SD 3.5 Large',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Stable Diffusion 3.5 Large. $0.035/megapixel',
                'released_at' => '2024-10-22',
            ],
            [
                'model_id' => 'fal-ai/stable-diffusion-v35-medium',
                'display_name' => 'SD 3.5 Medium',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Stable Diffusion 3.5 Medium. $0.035/megapixel',
                'released_at' => '2024-10-22',
            ],
            [
                'model_id' => 'fal-ai/fast-sdxl',
                'display_name' => 'Fast SDXL',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Optimized SDXL. $0.003/megapixel',
                'released_at' => '2023-07-26',
            ],

            // ============================================
            // Specialized Image Models
            // ============================================
            [
                'model_id' => 'fal-ai/recraft-v3',
                'display_name' => 'Recraft V3',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Design-focused, great text rendering. $0.04/megapixel',
                'released_at' => '2024-10-29',
            ],
            [
                'model_id' => 'fal-ai/ideogram/v2/turbo',
                'display_name' => 'Ideogram V2 Turbo',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Excellent text-in-image. $0.01/megapixel',
                'released_at' => '2024-11-20',
            ],
            [
                'model_id' => 'fal-ai/aura-flow',
                'display_name' => 'AuraFlow',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Open-source flow model. $0.025/megapixel',
                'released_at' => '2024-06-26',
            ],

            // ============================================
            // Image Editing & Enhancement
            // ============================================
            [
                'model_id' => 'fal-ai/flux-pro/v1/fill',
                'display_name' => 'Flux Pro Fill (Inpainting)',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Inpainting/outpainting. $0.05/megapixel',
                'released_at' => '2024-10-15',
            ],
            [
                'model_id' => 'fal-ai/clarity-upscaler',
                'display_name' => 'Clarity Upscaler',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'High-quality upscaling. $0.04/megapixel output',
                'released_at' => '2024-06-01',
            ],
            [
                'model_id' => 'fal-ai/face-swap',
                'display_name' => 'Face Swap',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Face swapping. $0.05/image',
                'released_at' => '2024-01-01',
            ],

            // ============================================
            // Video Generation
            // ============================================
            [
                'model_id' => 'fal-ai/kling-video/v1.6/pro',
                'display_name' => 'Kling Video 1.6 Pro',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'High quality video. $0.18/second',
                'released_at' => '2025-01-20',
            ],
            [
                'model_id' => 'fal-ai/minimax-video',
                'display_name' => 'MiniMax Video',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Text/image to video. $0.14/second',
                'released_at' => '2024-12-15',
            ],
            [
                'model_id' => 'fal-ai/luma-dream-machine',
                'display_name' => 'Luma Dream Machine',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'AI video generation. Check pricing',
                'released_at' => '2024-06-12',
            ],
        ];

        foreach ($models as $model) {
            AiModel::updateOrCreate(
                ['model_id' => $model['model_id']],
                array_merge($model, ['ai_provider_id' => $provider->id])
            );
        }
    }
}
