<?php

declare(strict_types=1);

namespace Alexandria\Core\Services\Writing;

use Alexandria\Core\Models\Writing\Work;
use Alexandria\Core\Models\Writing\WorkSection;
use Alexandria\Core\Models\Writing\WorkSectionEntryMention;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\DB;
use InvalidArgumentException;
use Throwable;

/**
 * Tree mutations for a work's sections — Stage 8g.1. Moves validate
 * same-work parentage and cycle safety (a section can never become
 * its own descendant); both touched sibling groups resequence to
 * dense 0-based positions. Slugs are work-scoped so moves never
 * change a section's URL.
 */
class SectionTreeService
{
    /**
     * Duplicate a section and its descendants beside the source
     * section. Content, craft fields, counts, and mention rows are
     * copied so the duplicate is immediately equivalent; slugs are
     * regenerated by WorkSection's model events.
     *
     * @throws Throwable
     */
    public function duplicateSubtree(WorkSection $section, string $rootTitle): WorkSection
    {
        return DB::transaction(function () use ($section, $rootTitle): WorkSection {
            $copy = $this->copyBranch(
                $section,
                $section->parent_id,
                $rootTitle,
                $section->position + 1,
            );

            $this->resequence($section->work_id, $section->parent_id, $copy->id, $section->position + 1);
            app(WorkSectionContentService::class)->refreshWorkRollup($section->work_id);

            return $copy->fresh();
        });
    }

    /**
     * @throws Throwable
     */
    public function move(WorkSection $section, ?int $newParentId, int $position): void
    {
        if ($newParentId !== null) {
            $parent = WorkSection::query()->findOrFail($newParentId);

            if ($parent->work_id !== $section->work_id) {
                throw new InvalidArgumentException('Target parent belongs to another work.');
            }

            if ($parent->id === $section->id || $this->isDescendantOf($parent, $section)) {
                throw new InvalidArgumentException('A section cannot become its own descendant.');
            }
        }

        DB::transaction(function () use ($section, $newParentId, $position): void {
            $oldParentId = $section->parent_id;

            $section->forceFill(['parent_id' => $newParentId, 'position' => $position])->save();

            $this->resequence($section->work_id, $newParentId, $section->id, $position);

            if ($oldParentId !== $newParentId) {
                $this->resequence($section->work_id, $oldParentId);
            }
        });
    }

    /**
     * @param  array<int, int>  $orderedIds
     *
     * @throws Throwable
     */
    public function reorder(Work $work, ?int $parentId, array $orderedIds): void
    {
        DB::transaction(function () use ($work, $parentId, $orderedIds): void {
            foreach (array_values($orderedIds) as $index => $id) {
                WorkSection::query()
                    ->where('work_id', $work->id)
                    ->where('parent_id', $parentId)
                    ->whereKey($id)
                    ->update(['position' => $index]);
            }
        });
    }

    /**
     * All ids in the live subtree rooted at $section, including $section
     * itself, collected breadth-first. Shared by deleteSubtree and the
     * delete-impact endpoint so "what would be removed" and "what IS
     * removed" can never drift apart.
     *
     * @return array<int, int>
     */
    public function subtreeIds(WorkSection $section): array
    {
        $ids = [$section->id];
        $frontier = [$section->id];

        while ($frontier !== []) {
            $frontier = WorkSection::query()
                ->whereIn('parent_id', $frontier)
                ->pluck('id')
                ->all();
            $ids = [...$ids, ...$frontier];
        }

        return $ids;
    }

    /**
     * Soft-delete a section and every descendant, then refresh the
     * work's cached word count. Descendants are collected breadth-first
     * over the live tree.
     *
     * @throws Throwable transaction failures bubble to the caller
     */
    public function deleteSubtree(WorkSection $section): void
    {
        DB::transaction(function () use ($section): void {
            $ids = $this->subtreeIds($section);

            // Per-model deletes are deliberate (model-event fidelity
            // for future observers) — don't bulk-optimize.
            WorkSection::query()->whereIn('id', $ids)->get()->each->delete();

            app(WorkSectionContentService::class)->refreshWorkRollup($section->work_id);
        });
    }

    /**
     * Soft-delete every live section belonging to a work — the section
     * side of a work-delete cascade. Callers wrap this alongside the
     * work's own delete() in one transaction (see WorkController::destroy)
     * so a work never gets soft-deleted while its sections stay live.
     *
     * @throws Throwable transaction failures bubble to the caller
     */
    public function deleteAllForWork(Work $work): void
    {
        DB::transaction(function () use ($work): void {
            // Per-model deletes, same rationale as deleteSubtree.
            $work->sections()->get()->each->delete();
        });
    }

    /**
     * Restore a trashed section, its trashed section-ancestors, and its
     * trashed work — a child cannot live under a trashed parent, and that
     * rule applies one level up too (a section cannot live under a
     * trashed work). Live ancestors are left untouched. Ancestors are
     * walked via withTrashed() since a trashed row's normal relations
     * are hidden by the SoftDeletes global scope.
     *
     * @throws Throwable transaction failures bubble to the caller
     */
    public function restoreWithAncestors(WorkSection $section): void
    {
        DB::transaction(function () use ($section): void {
            $work = Work::withTrashed()->findOrFail($section->work_id);

            if ($work->trashed()) {
                $work->restore();
            }

            $ancestorIds = [];
            $current = $section;

            while ($current->parent_id !== null) {
                $parent = WorkSection::withTrashed()->find($current->parent_id);

                if ($parent === null) {
                    break;
                }

                $ancestorIds[] = $parent->id;
                $current = $parent;
            }

            if ($ancestorIds !== []) {
                WorkSection::withTrashed()
                    ->whereIn('id', $ancestorIds)
                    ->whereNotNull('deleted_at')
                    ->get()
                    ->each->restore();
            }

            if ($section->trashed()) {
                $section->restore();
            }
        });
    }

    /**
     * Restore a trashed work plus every one of its trashed sections.
     *
     * Chosen over "only sections deleted in the same cascade window":
     * per-model deletes inside deleteAllForWork()/deleteSubtree() write
     * their deleted_at timestamps in a loop, and DB timestamp columns
     * commonly round to whole seconds — a window match would be an
     * unreliable proxy for "was this section deleted as part of this
     * work-delete". Restoring every trashed section for the work is
     * simple, deterministic, and testable, and matches what the user
     * sees in the workspace immediately before the work was deleted.
     * The tradeoff: a section the user independently trashed BEFORE
     * deleting the whole work comes back too — an accepted edge case
     * (it can be re-deleted from the workspace afterward).
     *
     * @throws Throwable transaction failures bubble to the caller
     */
    public function restoreAllForWork(Work $work): void
    {
        DB::transaction(function () use ($work): void {
            if ($work->trashed()) {
                $work->restore();
            }

            WorkSection::withTrashed()
                ->where('work_id', $work->id)
                ->whereNotNull('deleted_at')
                ->get()
                ->each->restore();
        });
    }

    private function isDescendantOf(WorkSection $candidate, WorkSection $ancestor): bool
    {
        $current = $candidate;

        while ($current->parent_id !== null) {
            if ($current->parent_id === $ancestor->id) {
                return true;
            }

            // A soft-deleted ancestor breaks the visible chain — the
            // candidate cannot be a (live) descendant past that point.
            $current = $current->parent;

            if ($current === null) {
                return false;
            }
        }

        return false;
    }

    private function copyBranch(WorkSection $source, ?int $parentId, string $title, int $position): WorkSection
    {
        $copy = $source->replicate(['slug']);
        $copy->forceFill([
            'parent_id' => $parentId,
            'title' => $title,
            'slug' => null,
            'position' => $position,
        ]);
        $copy->save();

        $source->entryMentions()->get()->each(function (WorkSectionEntryMention $mention) use ($copy): void {
            $copy->entryMentions()->create([
                'entry_id' => $mention->entry_id,
                'source' => $mention->source,
                'mention_count' => $mention->mention_count,
            ]);
        });

        WorkSection::query()
            ->where('parent_id', $source->id)
            ->orderBy('position')
            ->orderBy('id')
            ->get()
            ->each(function (WorkSection $child) use ($copy): void {
                $this->copyBranch($child, $copy->id, $child->title, $child->position);
            });

        return $copy;
    }

    /**
     * Rewrite a sibling group to dense 0-based positions. When a moved
     * section is supplied it is held at its requested slot and the
     * remaining siblings fill around it.
     */
    private function resequence(int $workId, ?int $parentId, ?int $movedId = null, ?int $movedPosition = null): void
    {
        /** @var Collection<int, WorkSection> $siblings */
        $siblings = WorkSection::query()
            ->where('work_id', $workId)
            ->where('parent_id', $parentId)
            ->when($movedId !== null, fn ($query) => $query->whereKeyNot($movedId))
            ->orderBy('position')
            ->orderBy('id')
            ->get();

        $slot = 0;

        foreach ($siblings as $sibling) {
            if ($movedPosition !== null && $slot === $movedPosition) {
                $slot++; // the moved section occupies this slot
            }

            if ($sibling->position !== $slot) {
                $sibling->forceFill(['position' => $slot])->save();
            }

            $slot++;
        }
    }
}
