<?php

declare(strict_types=1);

namespace Alexandria\Core\Models\Notable;

use Alexandria\Core\Database\Factories\Notable\AiReviewCommandFactory;
use Alexandria\Core\Models\Framework\Project;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Foundation\Auth\User;
use Illuminate\Support\Carbon;

/**
 * AI Review Command Model
 *
 * Represents a command generated by AI that needs user review before execution.
 * Provides flexible storage for both valid and malformed commands.
 *
 * @property int $id
 * @property string $batch_id
 * @property int $user_id
 * @property int|null $project_id
 * @property array|null $context
 * @property string|null $action_type
 * @property array|null $payload
 * @property string|null $reasoning
 * @property bool $is_active
 * @property string $status
 * @property string|null $failure_reason
 * @property Carbon|null $executed_at
 * @property array|null $raw_command
 * @property array|null $validation_errors
 * @property int $order_index
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read User|null $user
 * @property-read Project|null $project
 *
 * @method static Builder<static> forBatch(string $batchId)
 * @method static Builder<static> active()
 * @method static Builder<static> readyForExecution()
 */
class AiReviewCommand extends Model
{
    use HasFactory;

    protected $table = 'ai_review_commands';

    protected $guarded = ['id'];

    protected static function newFactory(): AiReviewCommandFactory
    {
        return AiReviewCommandFactory::new();
    }

    protected function casts(): array
    {
        return [
            'context' => 'array',
            'payload' => 'array',
            'raw_command' => 'array',
            'validation_errors' => 'array',
            'is_active' => 'boolean',
            'executed_at' => 'datetime',
            'order_index' => 'integer',
        ];
    }

    /**
     * The user who created this command review.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(config('alexandria.models.user'), 'user_id');
    }

    /**
     * The project this command belongs to.
     */
    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }

    /**
     * Check if this command is ready for execution.
     */
    public function isReadyForExecution(): bool
    {
        return $this->is_active && $this->status === 'approved' && $this->action_type !== null;
    }

    /**
     * Check if this command has validation errors (malformed).
     */
    public function hasValidationErrors(): bool
    {
        return ! empty($this->validation_errors);
    }

    /**
     * Get human-readable action name.
     */
    public function getActionDisplayName(): string
    {
        if (! $this->action_type) {
            return 'Invalid Command';
        }

        return match ($this->action_type) {
            'create_entry' => 'Create New Entry',
            'transfer_note' => 'Move Note',
            'copy_note' => 'Copy Note',
            'create_relationship' => 'Create Relationship',
            default => ucfirst(str_replace('_', ' ', $this->action_type)),
        };
    }

    /**
     * Scope to get commands for a specific batch.
     */
    public function scopeForBatch(Builder $query, string $batchId): Builder
    {
        return $query->where('batch_id', $batchId);
    }

    /**
     * Scope to get active commands only.
     */
    public function scopeActive(Builder $query): Builder
    {
        return $query->where('is_active', true);
    }

    /**
     * Scope to get commands ready for execution.
     */
    public function scopeReadyForExecution(Builder $query): Builder
    {
        return $query->where('is_active', true)
            ->where('status', 'approved')
            ->whereNotNull('action_type');
    }
}
