<?php

declare(strict_types=1);

namespace Alexandria\Core\Database\Seeders\AiModels;

use Alexandria\Core\Models\AiModel;
use Alexandria\Core\Models\AiProvider;
use Illuminate\Database\Seeder;

/**
 * fal.ai model catalog (Flux, Stable Diffusion, Z-Image, Recraft, Ideogram,
 * Seedream, Nano Banana, video gen via Kling/Wan/Veo/Sora/MiniMax/Luma).
 *
 * Pricing snapshot: 2026-05-05 from https://fal.ai/pricing + https://fal.ai/explore/models.
 * fal aggregates third-party model providers, so the canonical catalog evolves
 * fastest here. Future direction: pull from fal's models API where available.
 */
class FalModelSeeder extends Seeder
{
    public function run(): void
    {
        $provider = AiProvider::where('slug', 'fal')->first();
        if (! $provider) {
            return;
        }

        foreach ($this->models() as $model) {
            AiModel::updateOrCreate(
                ['model_id' => $model['model_id']],
                array_merge($model, ['ai_provider_id' => $provider->id])
            );
        }
    }

    /** @return array<int, array<string, mixed>> */
    private function models(): array
    {
        return [
            // Flux series — Black Forest Labs
            [
                'model_id' => 'fal-ai/flux-2/pro',
                'display_name' => 'FLUX.2 Pro',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.03/megapixel. Latest Flux flagship.',
                'released_at' => '2026-02-15',
            ],
            [
                'model_id' => 'fal-ai/flux-pro/v1.1-ultra',
                'display_name' => 'Flux Pro 1.1 Ultra',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.06/megapixel. Superseded by FLUX.2 Pro.',
                'released_at' => '2024-11-01',
            ],
            [
                'model_id' => 'fal-ai/flux-pro',
                'display_name' => 'Flux Pro',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.05/megapixel.',
                'released_at' => '2024-08-01',
            ],
            [
                'model_id' => 'fal-ai/flux-pro/v1/fill',
                'display_name' => 'Flux Pro Fill (Inpainting)',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.05/megapixel. Inpainting + outpainting.',
                'released_at' => '2024-10-15',
            ],
            [
                'model_id' => 'fal-ai/flux-kontext-pro',
                'display_name' => 'Flux Kontext Pro',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.04/image. Context-aware editing + variations.',
                'released_at' => '2025-08-01',
            ],
            [
                'model_id' => 'fal-ai/flux/dev',
                'display_name' => 'Flux Dev',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.025/megapixel. Development model.',
                'released_at' => '2024-08-01',
            ],
            [
                'model_id' => 'fal-ai/flux/schnell',
                'display_name' => 'Flux Schnell',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.003/megapixel. Fast generation.',
                'released_at' => '2024-08-01',
            ],

            // Seedream series
            [
                'model_id' => 'fal-ai/seedream-4.5',
                'display_name' => 'Seedream 4.5',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.04/image. Latest Seedream — image + image-to-video.',
                'released_at' => '2026-03-01',
            ],
            [
                'model_id' => 'fal-ai/seedream-v4',
                'display_name' => 'Seedream V4',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.03/image. Text-to-image.',
                'released_at' => '2025-11-15',
            ],

            // Nano Banana family (now via fal as well)
            [
                'model_id' => 'fal-ai/nano-banana-pro',
                'display_name' => 'Nano Banana Pro (via fal)',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Routed through fal. Native image gen w/ thinking.',
                'released_at' => '2025-11-18',
            ],
            [
                'model_id' => 'fal-ai/nano-banana-2',
                'display_name' => 'Nano Banana 2',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.0398/image. Fast text-to-image.',
                'released_at' => '2026-01-20',
            ],

            // Other image models
            [
                'model_id' => 'fal-ai/qwen-image',
                'display_name' => 'Qwen Image',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.02/megapixel.',
                'released_at' => '2025-09-01',
            ],
            [
                'model_id' => 'fal-ai/recraft-v3',
                'display_name' => 'Recraft V3',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.04/megapixel. Design-focused, great text rendering.',
                'released_at' => '2024-10-29',
            ],
            [
                'model_id' => 'fal-ai/ideogram/v2/turbo',
                'display_name' => 'Ideogram V2 Turbo',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.01/megapixel. Excellent text-in-image rendering.',
                'released_at' => '2024-11-20',
            ],
            [
                'model_id' => 'fal-ai/z-image/turbo',
                'display_name' => 'Z-Image Turbo',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '6B param, super fast. $0.005/megapixel.',
                'released_at' => '2025-01-15',
            ],
            [
                'model_id' => 'fal-ai/stable-diffusion-v35-large',
                'display_name' => 'SD 3.5 Large',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.035/megapixel.',
                'released_at' => '2024-10-22',
            ],
            [
                'model_id' => 'fal-ai/fast-sdxl',
                'display_name' => 'Fast SDXL',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.003/megapixel. Optimized SDXL.',
                'released_at' => '2023-07-26',
            ],

            // Image enhancement
            [
                'model_id' => 'fal-ai/clarity-upscaler',
                'display_name' => 'Clarity Upscaler',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.04/megapixel output. High-quality upscaling.',
                'released_at' => '2024-06-01',
            ],

            // Video generation
            [
                'model_id' => 'fal-ai/wan-2.5',
                'display_name' => 'Wan 2.5',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.05/sec. Text-to-video.',
                'released_at' => '2026-01-10',
            ],
            [
                'model_id' => 'fal-ai/kling-video/v3.0',
                'display_name' => 'Kling 3.0 Pro',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Latest Kling. Image + image-to-video.',
                'released_at' => '2026-02-01',
            ],
            [
                'model_id' => 'fal-ai/kling-video/v2.5/turbo-pro',
                'display_name' => 'Kling 2.5 Turbo Pro',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.07/sec. Image-to-video.',
                'released_at' => '2025-10-01',
            ],
            [
                'model_id' => 'fal-ai/kling-video/v1.6/pro',
                'display_name' => 'Kling Video 1.6 Pro',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.18/sec. High quality.',
                'released_at' => '2025-01-20',
            ],
            [
                'model_id' => 'fal-ai/veo-3',
                'display_name' => 'Veo 3 (via fal)',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.40/sec. Image-to-video routed through fal.',
                'released_at' => '2025-08-01',
            ],
            [
                'model_id' => 'fal-ai/ovi',
                'display_name' => 'Ovi',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.20/video. Video generation.',
                'released_at' => '2025-09-01',
            ],
            [
                'model_id' => 'fal-ai/minimax-video',
                'display_name' => 'MiniMax Video',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.14/sec. Text/image-to-video.',
                'released_at' => '2024-12-15',
            ],
            [
                'model_id' => 'fal-ai/luma-dream-machine',
                'display_name' => 'Luma Dream Machine',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'AI video generation.',
                'released_at' => '2024-06-12',
            ],
        ];
    }
}
