<?php

declare(strict_types=1);

namespace Alexandria\Core\Database\Seeders\AiModels;

use Alexandria\Core\Models\AiModel;
use Alexandria\Core\Models\AiProvider;
use Illuminate\Database\Seeder;

/**
 * Google AI model catalog (Gemini, Imagen, Veo, Lyria, Gemma).
 *
 * Pricing snapshot: 2026-05-05 from https://ai.google.dev/gemini-api/docs/pricing.
 * Future direction: pull from provider APIs where available — Google publishes
 * model metadata via the Gemini API, but pricing is not part of that surface.
 * For now, seed-as-snapshot is the simplest contract; refresh on each release.
 */
class GoogleModelSeeder extends Seeder
{
    public function run(): void
    {
        $provider = AiProvider::where('slug', 'google')->first();
        if (! $provider) {
            return;
        }

        foreach ($this->models() as $model) {
            AiModel::updateOrCreate(
                ['model_id' => $model['model_id']],
                array_merge($model, ['ai_provider_id' => $provider->id])
            );
        }
    }

    /** @return array<int, array<string, mixed>> */
    private function models(): array
    {
        return [
            // Gemini 3.1 series — current flagship (Apr 2026)
            [
                'model_id' => 'gemini-3.1-pro-preview',
                'display_name' => 'Gemini 3.1 Pro Preview',
                'category' => 'general',
                'context_window' => 1048576,
                'input_price_per_million' => 2.00,
                'output_price_per_million' => 12.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Most intelligent. Long context (>200K): $4/$18. Thinking, vision, agentic, search grounding.',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use', 'agentic', 'search_grounding'],
                'released_at' => '2026-03-15',
            ],
            [
                'model_id' => 'gemini-3.1-flash-lite-preview',
                'display_name' => 'Gemini 3.1 Flash-Lite Preview',
                'category' => 'fast',
                'context_window' => 1048576,
                'input_price_per_million' => 0.25,
                'output_price_per_million' => 1.50,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Cost-efficient agentic + translation. Audio input: $0.50/MTok.',
                'capabilities' => ['vision', 'tool_use', 'search_grounding'],
                'released_at' => '2026-03-15',
            ],

            // Gemini 3 series
            [
                'model_id' => 'gemini-3-pro-preview',
                'display_name' => 'Gemini 3 Pro Preview',
                'category' => 'general',
                'context_window' => 1048576,
                'input_price_per_million' => 2.00,
                'output_price_per_million' => 12.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Superseded by 3.1 Pro. 65K output. Thinking, search grounding.',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use', 'agentic', 'search_grounding'],
                'released_at' => '2025-11-18',
            ],
            [
                'model_id' => 'gemini-3-flash-preview',
                'display_name' => 'Gemini 3 Flash Preview',
                'category' => 'fast',
                'context_window' => 1048576,
                'input_price_per_million' => 0.50,
                'output_price_per_million' => 3.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Real-time dialogue, search grounding, multimodal. Audio input: $1.00/MTok.',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use', 'search_grounding'],
                'released_at' => '2025-12-19',
            ],

            // Gemini 2.5 series — stable workhorses
            [
                'model_id' => 'gemini-2.5-pro',
                'display_name' => 'Gemini 2.5 Pro',
                'category' => 'general',
                'context_window' => 1048576,
                'input_price_per_million' => 1.25,
                'output_price_per_million' => 10.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Long context (>200K): $2.50/$15. Coding + complex reasoning.',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use', 'search_grounding'],
                'released_at' => '2025-06-17',
            ],
            [
                'model_id' => 'gemini-2.5-flash',
                'display_name' => 'Gemini 2.5 Flash',
                'category' => 'fast',
                'context_window' => 1048576,
                'input_price_per_million' => 0.30,
                'output_price_per_million' => 2.50,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Best price-performance. Hybrid reasoning, thinking budgets. Audio input: $1.00/MTok.',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use', 'search_grounding'],
                'released_at' => '2025-06-17',
            ],
            [
                'model_id' => 'gemini-2.5-flash-lite',
                'display_name' => 'Gemini 2.5 Flash Lite',
                'category' => 'fast',
                'context_window' => 1048576,
                'input_price_per_million' => 0.10,
                'output_price_per_million' => 0.40,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Most cost-effective Gemini 2.5. Audio input: $0.30/MTok.',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use', 'search_grounding'],
                'released_at' => '2025-06-17',
            ],

            // Latest aliases — auto-updated, not pinnable
            [
                'model_id' => 'gemini-flash-latest',
                'display_name' => 'Gemini Flash Latest',
                'category' => 'fast',
                'context_window' => 1048576,
                'input_price_per_million' => 0.30,
                'output_price_per_million' => 2.50,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Alias → latest stable flash. Hot-swapped with 2-week notice.',
                'capabilities' => ['extended_thinking', 'vision', 'tool_use'],
                'released_at' => '2025-06-17',
            ],
            [
                'model_id' => 'gemini-flash-lite-latest',
                'display_name' => 'Gemini Flash Lite Latest',
                'category' => 'fast',
                'context_window' => 1048576,
                'input_price_per_million' => 0.10,
                'output_price_per_million' => 0.40,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Alias → latest stable flash-lite. Hot-swapped with 2-week notice.',
                'released_at' => '2025-06-17',
            ],

            // Gemini 2.0 series — deprecated, sunset Jun 1 2026
            [
                'model_id' => 'gemini-2.0-flash',
                'display_name' => 'Gemini 2.0 Flash',
                'category' => 'fast',
                'context_window' => 1048576,
                'input_price_per_million' => 0.10,
                'output_price_per_million' => 0.40,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => false,
                'notes' => 'DEPRECATED — sunset 2026-06-01. Migrate to Gemini 2.5 Flash.',
                'released_at' => '2025-02-25',
            ],
            [
                'model_id' => 'gemini-2.0-flash-lite',
                'display_name' => 'Gemini 2.0 Flash Lite',
                'category' => 'fast',
                'context_window' => 1048576,
                'input_price_per_million' => 0.075,
                'output_price_per_million' => 0.30,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => false,
                'notes' => 'DEPRECATED — sunset 2026-06-01. Migrate to Gemini 2.5 Flash Lite.',
                'released_at' => '2025-02-25',
            ],

            // Image generation
            [
                'model_id' => 'gemini-3.1-flash-image-preview',
                'display_name' => 'Gemini 3.1 Flash Image Preview',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => 0.50,
                'output_price_per_million' => 60.00,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_flagship' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Native image generation, speed-optimized.',
                'released_at' => '2026-03-15',
            ],
            [
                'model_id' => 'gemini-3-pro-image-preview',
                'display_name' => 'Nano Banana Pro',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => 2.00,
                'output_price_per_million' => 120.00,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Native image generation with Thinking. High-fidelity text rendering.',
                'capabilities' => ['image_generation', 'vision', 'extended_thinking'],
                'released_at' => '2025-11-18',
            ],
            [
                'model_id' => 'gemini-2.5-flash-image',
                'display_name' => 'Nano Banana',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => 0.30,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Fast native image generation. $0.039 per image output.',
                'released_at' => '2025-11-18',
            ],
            [
                'model_id' => 'imagen-4.0-fast-generate-001',
                'display_name' => 'Imagen 4 Fast',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.02/image. Fastest Imagen 4 tier.',
                'released_at' => '2025-11-18',
            ],
            [
                'model_id' => 'imagen-4.0-generate-001',
                'display_name' => 'Imagen 4',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.04/image. Standard tier with improved text rendering.',
                'released_at' => '2025-11-18',
            ],
            [
                'model_id' => 'imagen-4.0-ultra-generate-001',
                'display_name' => 'Imagen 4 Ultra',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_flagship' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.06/image. Highest quality Imagen 4 tier.',
                'released_at' => '2025-11-18',
            ],

            // Video generation
            [
                'model_id' => 'veo-3.1-generate-preview',
                'display_name' => 'Veo 3.1 Standard',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.40/sec standard, $0.60/sec premium. Generates with native audio.',
                'released_at' => '2025-12-19',
            ],
            [
                'model_id' => 'veo-3.1-fast-generate-preview',
                'display_name' => 'Veo 3.1 Fast',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.05–$0.30/sec depending on resolution.',
                'released_at' => '2025-12-19',
            ],
            [
                'model_id' => 'veo-3.1-lite-generate-preview',
                'display_name' => 'Veo 3.1 Lite',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Lower-resolution, cost-efficient Veo 3.1 tier.',
                'released_at' => '2025-12-19',
            ],
            [
                'model_id' => 'veo-3.0-generate-001',
                'display_name' => 'Veo 3 Standard',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.40/sec. Generates with native audio.',
                'released_at' => '2025-08-01',
            ],
            [
                'model_id' => 'veo-2.0-generate-001',
                'display_name' => 'Veo 2',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.35/sec. No audio.',
                'released_at' => '2025-05-20',
            ],

            // Audio
            [
                'model_id' => 'gemini-3.1-flash-live-preview',
                'display_name' => 'Gemini 3.1 Flash Live',
                'category' => 'audio',
                'context_window' => null,
                'input_price_per_million' => 0.75,
                'output_price_per_million' => 4.50,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Real-time audio-to-audio. Audio input: $3/MTok or $0.005/min. Audio output: $12/MTok.',
                'capabilities' => ['real_time_audio', 'vision'],
                'released_at' => '2026-03-15',
            ],
            [
                'model_id' => 'gemini-3.1-flash-tts-preview',
                'display_name' => 'Gemini 3.1 Flash TTS',
                'category' => 'audio',
                'context_window' => null,
                'input_price_per_million' => 1.00,
                'output_price_per_million' => 20.00,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Text-to-speech, low-latency, controllable speech.',
                'released_at' => '2026-03-15',
            ],
            [
                'model_id' => 'gemini-2.5-flash-native-audio-preview',
                'display_name' => 'Gemini 2.5 Flash Native Audio',
                'category' => 'audio',
                'context_window' => null,
                'input_price_per_million' => 0.50,
                'output_price_per_million' => 2.00,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Audio input: $3/MTok, audio output: $12/MTok. Natural pacing.',
                'released_at' => '2025-06-17',
            ],

            // Music generation
            [
                'model_id' => 'lyria-3-clip-preview',
                'display_name' => 'Lyria 3 Clip',
                'category' => 'audio',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Music generation. $0.04 per 30-second clip.',
                'released_at' => '2026-03-15',
            ],
            [
                'model_id' => 'lyria-3-pro-preview',
                'display_name' => 'Lyria 3 Pro',
                'category' => 'audio',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_flagship' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Music generation. $0.08 per full song.',
                'released_at' => '2026-03-15',
            ],

            // Embeddings
            [
                'model_id' => 'gemini-embedding-2',
                'display_name' => 'Gemini Embedding 2',
                'category' => 'embedding',
                'context_window' => null,
                'input_price_per_million' => 0.20,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Multimodal embeddings (text/image/audio/video/PDF). Image: $0.45/MTok. Audio: $6.50/MTok.',
                'released_at' => '2026-02-15',
            ],
            [
                'model_id' => 'gemini-embedding-001',
                'display_name' => 'Gemini Embedding',
                'category' => 'embedding',
                'context_window' => null,
                'input_price_per_million' => 0.15,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Text embeddings. Batch: $0.075/MTok.',
                'released_at' => '2025-06-17',
            ],

            // Specialized
            [
                'model_id' => 'gemini-2.5-computer-use-preview',
                'display_name' => 'Gemini 2.5 Computer Use',
                'category' => 'agent',
                'context_window' => 200000,
                'input_price_per_million' => 1.25,
                'output_price_per_million' => 10.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Browser control + task automation. Long context (>200K): $2.50/$15.',
                'capabilities' => ['vision', 'tool_use', 'computer_use'],
                'released_at' => '2025-10-15',
            ],
            [
                'model_id' => 'gemini-robotics-er-1.6-preview',
                'display_name' => 'Gemini Robotics-ER 1.6',
                'category' => 'agent',
                'context_window' => null,
                'input_price_per_million' => 1.00,
                'output_price_per_million' => 5.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Embodied reasoning, physical-world interaction. Audio: $2/MTok.',
                'capabilities' => ['vision', 'tool_use', 'embodied_reasoning'],
                'released_at' => '2026-01-20',
            ],

            // Open models
            [
                'model_id' => 'gemma-4',
                'display_name' => 'Gemma 4',
                'category' => 'general',
                'context_window' => 128000,
                'input_price_per_million' => 0.00,
                'output_price_per_million' => 0.00,
                'supports_json_mode' => true,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Free open-source model. Lightweight.',
                'released_at' => '2026-02-01',
            ],
            [
                'model_id' => 'gemma-3',
                'display_name' => 'Gemma 3',
                'category' => 'general',
                'context_window' => 128000,
                'input_price_per_million' => 0.00,
                'output_price_per_million' => 0.00,
                'supports_json_mode' => true,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Free open model. Predecessor to Gemma 4.',
                'released_at' => '2025-03-12',
            ],
        ];
    }
}
