<?php

declare(strict_types=1);

namespace Alexandria\Core\Database\Seeders\AiModels;

use Alexandria\Core\Models\AiModel;
use Alexandria\Core\Models\AiProvider;
use Illuminate\Database\Seeder;

/**
 * OpenAI model catalog (GPT-5.x, o-series, GPT-4.x, image, video, audio, embeddings).
 *
 * Pricing snapshot: 2026-05-05 from https://developers.openai.com/api/docs/pricing.
 * GPT-5.5 is current flagship as of Apr 2026; GPT-5.4 family released Mar 2026.
 */
class OpenAiModelSeeder extends Seeder
{
    public function run(): void
    {
        $provider = AiProvider::where('slug', 'openai')->first();
        if (! $provider) {
            return;
        }

        foreach ($this->models() as $model) {
            AiModel::updateOrCreate(
                ['model_id' => $model['model_id']],
                array_merge($model, ['ai_provider_id' => $provider->id])
            );
        }
    }

    /** @return array<int, array<string, mixed>> */
    private function models(): array
    {
        return [
            // GPT-5.5 series — current flagship (Apr 2026)
            [
                'model_id' => 'gpt-5.5',
                'display_name' => 'GPT-5.5',
                'category' => 'general',
                'context_window' => 256000,
                'input_price_per_million' => 5.00,
                'output_price_per_million' => 30.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Latest flagship. Cached: $0.50/MTok.',
                'released_at' => '2026-04-02',
            ],
            [
                'model_id' => 'gpt-5.5-pro',
                'display_name' => 'GPT-5.5 Pro',
                'category' => 'creative',
                'context_window' => 256000,
                'input_price_per_million' => 30.00,
                'output_price_per_million' => 180.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Premium quality output for the most demanding tasks.',
                'released_at' => '2026-04-02',
            ],

            // GPT-5.4 series — Mar 2026 release
            [
                'model_id' => 'gpt-5.4',
                'display_name' => 'GPT-5.4',
                'category' => 'general',
                'context_window' => 256000,
                'input_price_per_million' => 2.50,
                'output_price_per_million' => 15.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Best balance. Cached: $0.25/MTok.',
                'released_at' => '2026-03-05',
            ],
            [
                'model_id' => 'gpt-5.4-mini',
                'display_name' => 'GPT-5.4 Mini',
                'category' => 'fast',
                'context_window' => 128000,
                'input_price_per_million' => 0.75,
                'output_price_per_million' => 4.50,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Fast + affordable. Cached: $0.075/MTok.',
                'released_at' => '2026-03-17',
            ],
            [
                'model_id' => 'gpt-5.4-nano',
                'display_name' => 'GPT-5.4 Nano',
                'category' => 'fast',
                'context_window' => 128000,
                'input_price_per_million' => 0.20,
                'output_price_per_million' => 1.25,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Most affordable. Cached: $0.02/MTok.',
                'released_at' => '2026-03-17',
            ],
            [
                'model_id' => 'gpt-5.4-pro',
                'display_name' => 'GPT-5.4 Pro',
                'category' => 'creative',
                'context_window' => 256000,
                'input_price_per_million' => 30.00,
                'output_price_per_million' => 180.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Premium quality. Same pricing as GPT-5.5 Pro.',
                'released_at' => '2026-03-05',
            ],

            // GPT-5.x earlier
            [
                'model_id' => 'gpt-5.2',
                'display_name' => 'GPT-5.2',
                'category' => 'general',
                'context_window' => 128000,
                'input_price_per_million' => 1.75,
                'output_price_per_million' => 14.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Cached: $0.175/MTok.',
                'released_at' => '2025-12-17',
            ],
            [
                'model_id' => 'gpt-5.1',
                'display_name' => 'GPT-5.1',
                'category' => 'general',
                'context_window' => 128000,
                'input_price_per_million' => 1.25,
                'output_price_per_million' => 10.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Cached: $0.125/MTok.',
                'released_at' => '2025-10-01',
            ],
            [
                'model_id' => 'gpt-5',
                'display_name' => 'GPT-5',
                'category' => 'general',
                'context_window' => 128000,
                'input_price_per_million' => 1.25,
                'output_price_per_million' => 10.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Cached: $0.125/MTok.',
                'released_at' => '2025-08-07',
            ],
            [
                'model_id' => 'gpt-5-mini',
                'display_name' => 'GPT-5 Mini',
                'category' => 'fast',
                'context_window' => 128000,
                'input_price_per_million' => 0.25,
                'output_price_per_million' => 2.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Cached: $0.025/MTok. Superseded by GPT-5.4 Mini.',
                'released_at' => '2025-08-07',
            ],
            [
                'model_id' => 'gpt-5-nano',
                'display_name' => 'GPT-5 Nano',
                'category' => 'fast',
                'context_window' => 128000,
                'input_price_per_million' => 0.05,
                'output_price_per_million' => 0.40,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Cached: $0.005/MTok. Superseded by GPT-5.4 Nano.',
                'released_at' => '2025-08-07',
            ],

            // O-series reasoning models
            [
                'model_id' => 'o3',
                'display_name' => 'O3',
                'category' => 'analyst',
                'context_window' => 200000,
                'input_price_per_million' => 2.00,
                'output_price_per_million' => 8.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Latest reasoning model. Cached: $0.50/MTok.',
                'released_at' => '2025-04-16',
            ],
            [
                'model_id' => 'o3-pro',
                'display_name' => 'O3 Pro',
                'category' => 'analyst',
                'context_window' => 200000,
                'input_price_per_million' => 20.00,
                'output_price_per_million' => 80.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Enhanced O3 reasoning.',
                'released_at' => '2025-06-10',
            ],
            [
                'model_id' => 'o3-mini',
                'display_name' => 'O3 Mini',
                'category' => 'analyst',
                'context_window' => 200000,
                'input_price_per_million' => 1.10,
                'output_price_per_million' => 4.40,
                'supports_json_mode' => true,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Fast reasoning. Cached: $0.55/MTok.',
                'released_at' => '2025-01-31',
            ],
            [
                'model_id' => 'o3-deep-research',
                'display_name' => 'O3 Deep Research',
                'category' => 'analyst',
                'context_window' => 200000,
                'input_price_per_million' => 5.00,
                'output_price_per_million' => 20.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Extended research mode.',
                'released_at' => '2025-06-26',
            ],
            [
                'model_id' => 'o4-mini',
                'display_name' => 'O4 Mini',
                'category' => 'analyst',
                'context_window' => 200000,
                'input_price_per_million' => 1.10,
                'output_price_per_million' => 4.40,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Latest mini reasoning. Cached: $0.275/MTok.',
                'released_at' => '2025-04-16',
            ],
            [
                'model_id' => 'o4-mini-deep-research',
                'display_name' => 'O4 Mini Deep Research',
                'category' => 'analyst',
                'context_window' => 200000,
                'input_price_per_million' => 1.00,
                'output_price_per_million' => 4.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Mini with deep research mode.',
                'released_at' => '2025-04-16',
            ],

            // Realtime + Audio
            [
                'model_id' => 'gpt-realtime-1.5',
                'display_name' => 'GPT Realtime 1.5',
                'category' => 'audio',
                'context_window' => 128000,
                'input_price_per_million' => 4.00,
                'output_price_per_million' => 16.00,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Audio I/O: $32/$64. Image input: $5/MTok. Cached audio: $0.40/MTok.',
                'released_at' => '2026-02-20',
            ],
            [
                'model_id' => 'gpt-realtime-mini',
                'display_name' => 'GPT Realtime Mini',
                'category' => 'audio',
                'context_window' => 128000,
                'input_price_per_million' => 0.60,
                'output_price_per_million' => 2.40,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Audio I/O: $10/$20 per MTok. Cached audio: $0.30/MTok.',
                'released_at' => '2025-03-20',
            ],
            [
                'model_id' => 'gpt-4o-transcribe',
                'display_name' => 'GPT-4o Transcribe',
                'category' => 'audio',
                'context_window' => null,
                'input_price_per_million' => 2.50,
                'output_price_per_million' => 10.00,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '~$0.006/min. Replaces whisper-1.',
                'released_at' => '2025-06-01',
            ],
            [
                'model_id' => 'gpt-4o-mini-transcribe',
                'display_name' => 'GPT-4o Mini Transcribe',
                'category' => 'audio',
                'context_window' => null,
                'input_price_per_million' => 1.25,
                'output_price_per_million' => 5.00,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '~$0.003/min. Cost-effective transcription.',
                'released_at' => '2025-06-01',
            ],

            // Image generation
            [
                'model_id' => 'gpt-image-2',
                'display_name' => 'GPT Image 2',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => 8.00,
                'output_price_per_million' => 30.00,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_flagship' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Latest image generation. Cached: $2/MTok.',
                'released_at' => '2026-04-10',
            ],
            [
                'model_id' => 'gpt-image-1.5',
                'display_name' => 'GPT Image 1.5',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => 8.00,
                'output_price_per_million' => 32.00,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Low: $0.009, Med: $0.034, High: $0.133 per image. Cached: $2/MTok.',
                'released_at' => '2025-12-17',
            ],
            [
                'model_id' => 'gpt-image-1-mini',
                'display_name' => 'GPT Image 1 Mini',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => 2.50,
                'output_price_per_million' => 8.00,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Low: $0.005, Med: $0.011, High: $0.036 per image. Cached: $0.25/MTok.',
                'released_at' => '2025-04-23',
            ],
            [
                'model_id' => 'gpt-image-1',
                'display_name' => 'GPT Image 1',
                'category' => 'image',
                'context_window' => null,
                'input_price_per_million' => 5.00,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Low: $0.011, Med: $0.042, High: $0.167 per image. Superseded by 1.5/2.',
                'released_at' => '2025-04-23',
            ],

            // Video generation
            [
                'model_id' => 'sora-2',
                'display_name' => 'Sora 2',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => '$0.10/second (720p).',
                'released_at' => '2025-12-17',
            ],
            [
                'model_id' => 'sora-2-pro',
                'display_name' => 'Sora 2 Pro',
                'category' => 'video',
                'context_window' => null,
                'input_price_per_million' => null,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_flagship' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => '$0.30/sec (720p), $0.50/sec (1024p), $0.70/sec (1080p).',
                'released_at' => '2025-12-17',
            ],

            // Embeddings
            [
                'model_id' => 'text-embedding-3-small',
                'display_name' => 'Text Embedding 3 Small',
                'category' => 'embedding',
                'context_window' => 8191,
                'input_price_per_million' => 0.02,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Batch: $0.01/MTok.',
                'released_at' => '2024-01-25',
            ],
            [
                'model_id' => 'text-embedding-3-large',
                'display_name' => 'Text Embedding 3 Large',
                'category' => 'embedding',
                'context_window' => 8191,
                'input_price_per_million' => 0.13,
                'output_price_per_million' => null,
                'supports_json_mode' => false,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Higher quality. Batch: $0.065/MTok.',
                'released_at' => '2024-01-25',
            ],

            // Codex (code-specialized)
            [
                'model_id' => 'gpt-5.3-codex',
                'display_name' => 'GPT-5.3 Codex',
                'category' => 'general',
                'context_window' => 128000,
                'input_price_per_million' => 1.75,
                'output_price_per_million' => 14.00,
                'supports_json_mode' => true,
                'supports_vision' => false,
                'is_recommended' => true,
                'is_active' => true,
                'notes' => 'Optimized for code.',
                'released_at' => '2026-01-15',
            ],
            [
                'model_id' => 'gpt-5.1-codex',
                'display_name' => 'GPT-5.1 Codex',
                'category' => 'general',
                'context_window' => 128000,
                'input_price_per_million' => 1.25,
                'output_price_per_million' => 10.00,
                'supports_json_mode' => true,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Cached: $0.125/MTok. Superseded by 5.3 Codex.',
                'released_at' => '2025-10-01',
            ],
            [
                'model_id' => 'gpt-5.1-codex-mini',
                'display_name' => 'GPT-5.1 Codex Mini',
                'category' => 'fast',
                'context_window' => 128000,
                'input_price_per_million' => 0.25,
                'output_price_per_million' => 2.00,
                'supports_json_mode' => true,
                'supports_vision' => false,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Fast code assistant.',
                'released_at' => '2025-10-01',
            ],

            // Computer Use
            [
                'model_id' => 'computer-use-preview',
                'display_name' => 'Computer Use Preview',
                'category' => 'agent',
                'context_window' => 128000,
                'input_price_per_million' => 1.50,
                'output_price_per_million' => 6.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Computer control agent.',
                'released_at' => '2025-03-27',
            ],

            // Legacy GPT-4o (kept for backward compatibility — prefer GPT-5.4+)
            [
                'model_id' => 'gpt-4o',
                'display_name' => 'GPT-4o',
                'category' => 'general',
                'context_window' => 128000,
                'input_price_per_million' => 2.50,
                'output_price_per_million' => 10.00,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Legacy. Cached: $1.25/MTok. Prefer GPT-5.4 family.',
                'released_at' => '2024-05-13',
            ],
            [
                'model_id' => 'gpt-4o-mini',
                'display_name' => 'GPT-4o Mini',
                'category' => 'fast',
                'context_window' => 128000,
                'input_price_per_million' => 0.15,
                'output_price_per_million' => 0.60,
                'supports_json_mode' => true,
                'supports_vision' => true,
                'is_recommended' => false,
                'is_active' => true,
                'notes' => 'Legacy. Cached: $0.075/MTok. Prefer GPT-5.4 Mini.',
                'released_at' => '2024-07-18',
            ],
        ];
    }
}
